apiVersion: v1
kind: Config

clusters:
- name: minikube
  cluster:
    server: https://192.168.49.2:8443
    insecure-skip-tls-verify: true

contexts:
- name: sa-context
  context:
    cluster: minikube
    namespace: mynamespace
    user: myexample-sa

current-context: sa-context

users:
- name: myexample-sa
  user:
    token: <TOKEN_HERE>
